name: Compiler

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: compiler 
        run: |
          pwd
          l
          export NDK_PROJECT_PATH=Android.mk
          ndk-build
          chmod 777 build.sh
          ./build.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: compiler
          path: ../libs/*
